//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JTB_Airline_Cruise.AirService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AirlineServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Record))]
    public partial class AirlineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback A_Debug_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookFlightOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastFlightIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddFlightOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateFlightOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFlightOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAirlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAirlinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAirlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAirlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookingCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightRevenueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecentBookingsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AirlineService() {
            this.Url = global::JTB_Airline_Cruise.Properties.Settings.Default.JTB_Airline_Cruise_AirService_AirlineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event A_Debug_TestCompletedEventHandler A_Debug_TestCompleted;
        
        /// <remarks/>
        public event GetFlightsCompletedEventHandler GetFlightsCompleted;
        
        /// <remarks/>
        public event BookFlightCompletedEventHandler BookFlightCompleted;
        
        /// <remarks/>
        public event GetLastFlightIDCompletedEventHandler GetLastFlightIDCompleted;
        
        /// <remarks/>
        public event AddFlightCompletedEventHandler AddFlightCompleted;
        
        /// <remarks/>
        public event AllFlightsCompletedEventHandler AllFlightsCompleted;
        
        /// <remarks/>
        public event GetFlightByIdCompletedEventHandler GetFlightByIdCompleted;
        
        /// <remarks/>
        public event UpdateFlightCompletedEventHandler UpdateFlightCompleted;
        
        /// <remarks/>
        public event DeleteFlightCompletedEventHandler DeleteFlightCompleted;
        
        /// <remarks/>
        public event AddAirlineCompletedEventHandler AddAirlineCompleted;
        
        /// <remarks/>
        public event GetAirlinesCompletedEventHandler GetAirlinesCompleted;
        
        /// <remarks/>
        public event DeleteAirlineCompletedEventHandler DeleteAirlineCompleted;
        
        /// <remarks/>
        public event UpdateAirlineCompletedEventHandler UpdateAirlineCompleted;
        
        /// <remarks/>
        public event AllBookingsCompletedEventHandler AllBookingsCompleted;
        
        /// <remarks/>
        public event GetBookingsCompletedEventHandler GetBookingsCompleted;
        
        /// <remarks/>
        public event GetBookingCountCompletedEventHandler GetBookingCountCompleted;
        
        /// <remarks/>
        public event GetFlightCountCompletedEventHandler GetFlightCountCompleted;
        
        /// <remarks/>
        public event GetFlightRevenueCompletedEventHandler GetFlightRevenueCompleted;
        
        /// <remarks/>
        public event GetRecentBookingsCompletedEventHandler GetRecentBookingsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/A_Debug_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Flight A_Debug_Test() {
            object[] results = this.Invoke("A_Debug_Test", new object[0]);
            return ((Flight)(results[0]));
        }
        
        /// <remarks/>
        public void A_Debug_TestAsync() {
            this.A_Debug_TestAsync(null);
        }
        
        /// <remarks/>
        public void A_Debug_TestAsync(object userState) {
            if ((this.A_Debug_TestOperationCompleted == null)) {
                this.A_Debug_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_Debug_TestOperationCompleted);
            }
            this.InvokeAsync("A_Debug_Test", new object[0], this.A_Debug_TestOperationCompleted, userState);
        }
        
        private void OnA_Debug_TestOperationCompleted(object arg) {
            if ((this.A_Debug_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_Debug_TestCompleted(this, new A_Debug_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlights", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Flight[] GetFlights(string Country, string City, string Date) {
            object[] results = this.Invoke("GetFlights", new object[] {
                        Country,
                        City,
                        Date});
            return ((Flight[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightsAsync(string Country, string City, string Date) {
            this.GetFlightsAsync(Country, City, Date, null);
        }
        
        /// <remarks/>
        public void GetFlightsAsync(string Country, string City, string Date, object userState) {
            if ((this.GetFlightsOperationCompleted == null)) {
                this.GetFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightsOperationCompleted);
            }
            this.InvokeAsync("GetFlights", new object[] {
                        Country,
                        City,
                        Date}, this.GetFlightsOperationCompleted, userState);
        }
        
        private void OnGetFlightsOperationCompleted(object arg) {
            if ((this.GetFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightsCompleted(this, new GetFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BookFlight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BookFlight(string FlightID, string Name, string DOB) {
            this.Invoke("BookFlight", new object[] {
                        FlightID,
                        Name,
                        DOB});
        }
        
        /// <remarks/>
        public void BookFlightAsync(string FlightID, string Name, string DOB) {
            this.BookFlightAsync(FlightID, Name, DOB, null);
        }
        
        /// <remarks/>
        public void BookFlightAsync(string FlightID, string Name, string DOB, object userState) {
            if ((this.BookFlightOperationCompleted == null)) {
                this.BookFlightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookFlightOperationCompleted);
            }
            this.InvokeAsync("BookFlight", new object[] {
                        FlightID,
                        Name,
                        DOB}, this.BookFlightOperationCompleted, userState);
        }
        
        private void OnBookFlightOperationCompleted(object arg) {
            if ((this.BookFlightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookFlightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastFlightID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLastFlightID() {
            object[] results = this.Invoke("GetLastFlightID", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastFlightIDAsync() {
            this.GetLastFlightIDAsync(null);
        }
        
        /// <remarks/>
        public void GetLastFlightIDAsync(object userState) {
            if ((this.GetLastFlightIDOperationCompleted == null)) {
                this.GetLastFlightIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastFlightIDOperationCompleted);
            }
            this.InvokeAsync("GetLastFlightID", new object[0], this.GetLastFlightIDOperationCompleted, userState);
        }
        
        private void OnGetLastFlightIDOperationCompleted(object arg) {
            if ((this.GetLastFlightIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastFlightIDCompleted(this, new GetLastFlightIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddFlight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddFlight(_Flight _flight) {
            this.Invoke("AddFlight", new object[] {
                        _flight});
        }
        
        /// <remarks/>
        public void AddFlightAsync(_Flight _flight) {
            this.AddFlightAsync(_flight, null);
        }
        
        /// <remarks/>
        public void AddFlightAsync(_Flight _flight, object userState) {
            if ((this.AddFlightOperationCompleted == null)) {
                this.AddFlightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddFlightOperationCompleted);
            }
            this.InvokeAsync("AddFlight", new object[] {
                        _flight}, this.AddFlightOperationCompleted, userState);
        }
        
        private void OnAddFlightOperationCompleted(object arg) {
            if ((this.AddFlightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddFlightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllFlights", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _Flight[] AllFlights() {
            object[] results = this.Invoke("AllFlights", new object[0]);
            return ((_Flight[])(results[0]));
        }
        
        /// <remarks/>
        public void AllFlightsAsync() {
            this.AllFlightsAsync(null);
        }
        
        /// <remarks/>
        public void AllFlightsAsync(object userState) {
            if ((this.AllFlightsOperationCompleted == null)) {
                this.AllFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllFlightsOperationCompleted);
            }
            this.InvokeAsync("AllFlights", new object[0], this.AllFlightsOperationCompleted, userState);
        }
        
        private void OnAllFlightsOperationCompleted(object arg) {
            if ((this.AllFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllFlightsCompleted(this, new AllFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlightById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Flight GetFlightById(int flightId) {
            object[] results = this.Invoke("GetFlightById", new object[] {
                        flightId});
            return ((Flight)(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightByIdAsync(int flightId) {
            this.GetFlightByIdAsync(flightId, null);
        }
        
        /// <remarks/>
        public void GetFlightByIdAsync(int flightId, object userState) {
            if ((this.GetFlightByIdOperationCompleted == null)) {
                this.GetFlightByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightByIdOperationCompleted);
            }
            this.InvokeAsync("GetFlightById", new object[] {
                        flightId}, this.GetFlightByIdOperationCompleted, userState);
        }
        
        private void OnGetFlightByIdOperationCompleted(object arg) {
            if ((this.GetFlightByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightByIdCompleted(this, new GetFlightByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateFlight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateFlight(_Flight _flight) {
            this.Invoke("UpdateFlight", new object[] {
                        _flight});
        }
        
        /// <remarks/>
        public void UpdateFlightAsync(_Flight _flight) {
            this.UpdateFlightAsync(_flight, null);
        }
        
        /// <remarks/>
        public void UpdateFlightAsync(_Flight _flight, object userState) {
            if ((this.UpdateFlightOperationCompleted == null)) {
                this.UpdateFlightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateFlightOperationCompleted);
            }
            this.InvokeAsync("UpdateFlight", new object[] {
                        _flight}, this.UpdateFlightOperationCompleted, userState);
        }
        
        private void OnUpdateFlightOperationCompleted(object arg) {
            if ((this.UpdateFlightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateFlightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFlight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteFlight(int flightId) {
            this.Invoke("DeleteFlight", new object[] {
                        flightId});
        }
        
        /// <remarks/>
        public void DeleteFlightAsync(int flightId) {
            this.DeleteFlightAsync(flightId, null);
        }
        
        /// <remarks/>
        public void DeleteFlightAsync(int flightId, object userState) {
            if ((this.DeleteFlightOperationCompleted == null)) {
                this.DeleteFlightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFlightOperationCompleted);
            }
            this.InvokeAsync("DeleteFlight", new object[] {
                        flightId}, this.DeleteFlightOperationCompleted, userState);
        }
        
        private void OnDeleteFlightOperationCompleted(object arg) {
            if ((this.DeleteFlightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFlightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAirline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddAirline(string airlineName) {
            this.Invoke("AddAirline", new object[] {
                        airlineName});
        }
        
        /// <remarks/>
        public void AddAirlineAsync(string airlineName) {
            this.AddAirlineAsync(airlineName, null);
        }
        
        /// <remarks/>
        public void AddAirlineAsync(string airlineName, object userState) {
            if ((this.AddAirlineOperationCompleted == null)) {
                this.AddAirlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAirlineOperationCompleted);
            }
            this.InvokeAsync("AddAirline", new object[] {
                        airlineName}, this.AddAirlineOperationCompleted, userState);
        }
        
        private void OnAddAirlineOperationCompleted(object arg) {
            if ((this.AddAirlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAirlineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirlines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Airline[] GetAirlines() {
            object[] results = this.Invoke("GetAirlines", new object[0]);
            return ((Airline[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAirlinesAsync() {
            this.GetAirlinesAsync(null);
        }
        
        /// <remarks/>
        public void GetAirlinesAsync(object userState) {
            if ((this.GetAirlinesOperationCompleted == null)) {
                this.GetAirlinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirlinesOperationCompleted);
            }
            this.InvokeAsync("GetAirlines", new object[0], this.GetAirlinesOperationCompleted, userState);
        }
        
        private void OnGetAirlinesOperationCompleted(object arg) {
            if ((this.GetAirlinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirlinesCompleted(this, new GetAirlinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAirline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteAirline(int airlineId) {
            object[] results = this.Invoke("DeleteAirline", new object[] {
                        airlineId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAirlineAsync(int airlineId) {
            this.DeleteAirlineAsync(airlineId, null);
        }
        
        /// <remarks/>
        public void DeleteAirlineAsync(int airlineId, object userState) {
            if ((this.DeleteAirlineOperationCompleted == null)) {
                this.DeleteAirlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAirlineOperationCompleted);
            }
            this.InvokeAsync("DeleteAirline", new object[] {
                        airlineId}, this.DeleteAirlineOperationCompleted, userState);
        }
        
        private void OnDeleteAirlineOperationCompleted(object arg) {
            if ((this.DeleteAirlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAirlineCompleted(this, new DeleteAirlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAirline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAirline(int airlineId, string airlineName) {
            this.Invoke("UpdateAirline", new object[] {
                        airlineId,
                        airlineName});
        }
        
        /// <remarks/>
        public void UpdateAirlineAsync(int airlineId, string airlineName) {
            this.UpdateAirlineAsync(airlineId, airlineName, null);
        }
        
        /// <remarks/>
        public void UpdateAirlineAsync(int airlineId, string airlineName, object userState) {
            if ((this.UpdateAirlineOperationCompleted == null)) {
                this.UpdateAirlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAirlineOperationCompleted);
            }
            this.InvokeAsync("UpdateAirline", new object[] {
                        airlineId,
                        airlineName}, this.UpdateAirlineOperationCompleted, userState);
        }
        
        private void OnUpdateAirlineOperationCompleted(object arg) {
            if ((this.UpdateAirlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAirlineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FlightBooking[] AllBookings() {
            object[] results = this.Invoke("AllBookings", new object[0]);
            return ((FlightBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void AllBookingsAsync() {
            this.AllBookingsAsync(null);
        }
        
        /// <remarks/>
        public void AllBookingsAsync(object userState) {
            if ((this.AllBookingsOperationCompleted == null)) {
                this.AllBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllBookingsOperationCompleted);
            }
            this.InvokeAsync("AllBookings", new object[0], this.AllBookingsOperationCompleted, userState);
        }
        
        private void OnAllBookingsOperationCompleted(object arg) {
            if ((this.AllBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllBookingsCompleted(this, new AllBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FlightBooking[] GetBookings(string passengerId) {
            object[] results = this.Invoke("GetBookings", new object[] {
                        passengerId});
            return ((FlightBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBookingsAsync(string passengerId) {
            this.GetBookingsAsync(passengerId, null);
        }
        
        /// <remarks/>
        public void GetBookingsAsync(string passengerId, object userState) {
            if ((this.GetBookingsOperationCompleted == null)) {
                this.GetBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookingsOperationCompleted);
            }
            this.InvokeAsync("GetBookings", new object[] {
                        passengerId}, this.GetBookingsOperationCompleted, userState);
        }
        
        private void OnGetBookingsOperationCompleted(object arg) {
            if ((this.GetBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookingsCompleted(this, new GetBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookingCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetBookingCount() {
            object[] results = this.Invoke("GetBookingCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookingCountAsync() {
            this.GetBookingCountAsync(null);
        }
        
        /// <remarks/>
        public void GetBookingCountAsync(object userState) {
            if ((this.GetBookingCountOperationCompleted == null)) {
                this.GetBookingCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookingCountOperationCompleted);
            }
            this.InvokeAsync("GetBookingCount", new object[0], this.GetBookingCountOperationCompleted, userState);
        }
        
        private void OnGetBookingCountOperationCompleted(object arg) {
            if ((this.GetBookingCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookingCountCompleted(this, new GetBookingCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlightCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFlightCount() {
            object[] results = this.Invoke("GetFlightCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightCountAsync() {
            this.GetFlightCountAsync(null);
        }
        
        /// <remarks/>
        public void GetFlightCountAsync(object userState) {
            if ((this.GetFlightCountOperationCompleted == null)) {
                this.GetFlightCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightCountOperationCompleted);
            }
            this.InvokeAsync("GetFlightCount", new object[0], this.GetFlightCountOperationCompleted, userState);
        }
        
        private void OnGetFlightCountOperationCompleted(object arg) {
            if ((this.GetFlightCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightCountCompleted(this, new GetFlightCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlightRevenue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float GetFlightRevenue() {
            object[] results = this.Invoke("GetFlightRevenue", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightRevenueAsync() {
            this.GetFlightRevenueAsync(null);
        }
        
        /// <remarks/>
        public void GetFlightRevenueAsync(object userState) {
            if ((this.GetFlightRevenueOperationCompleted == null)) {
                this.GetFlightRevenueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightRevenueOperationCompleted);
            }
            this.InvokeAsync("GetFlightRevenue", new object[0], this.GetFlightRevenueOperationCompleted, userState);
        }
        
        private void OnGetFlightRevenueOperationCompleted(object arg) {
            if ((this.GetFlightRevenueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightRevenueCompleted(this, new GetFlightRevenueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecentBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FlightBooking[] GetRecentBookings() {
            object[] results = this.Invoke("GetRecentBookings", new object[0]);
            return ((FlightBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecentBookingsAsync() {
            this.GetRecentBookingsAsync(null);
        }
        
        /// <remarks/>
        public void GetRecentBookingsAsync(object userState) {
            if ((this.GetRecentBookingsOperationCompleted == null)) {
                this.GetRecentBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecentBookingsOperationCompleted);
            }
            this.InvokeAsync("GetRecentBookings", new object[0], this.GetRecentBookingsOperationCompleted, userState);
        }
        
        private void OnGetRecentBookingsOperationCompleted(object arg) {
            if ((this.GetRecentBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecentBookingsCompleted(this, new GetRecentBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Flight {
        
        private int flightIDField;
        
        private Airline airlineField;
        
        private string departureCityField;
        
        private string destinationCityField;
        
        private System.DateTime departureDateField;
        
        private System.DateTime returnDateField;
        
        private FlightType[] flightTypeField;
        
        private FlightClass[] flightClassField;
        
        private FlightPrice[] flightPriceField;
        
        private string planeField;
        
        /// <remarks/>
        public int FlightID {
            get {
                return this.flightIDField;
            }
            set {
                this.flightIDField = value;
            }
        }
        
        /// <remarks/>
        public Airline Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureCity {
            get {
                return this.departureCityField;
            }
            set {
                this.departureCityField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReturnDate {
            get {
                return this.returnDateField;
            }
            set {
                this.returnDateField = value;
            }
        }
        
        /// <remarks/>
        public FlightType[] FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        public FlightClass[] FlightClass {
            get {
                return this.flightClassField;
            }
            set {
                this.flightClassField = value;
            }
        }
        
        /// <remarks/>
        public FlightPrice[] FlightPrice {
            get {
                return this.flightPriceField;
            }
            set {
                this.flightPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Plane {
            get {
                return this.planeField;
            }
            set {
                this.planeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Airline {
        
        private int airlineIDField;
        
        private string airlineNameField;
        
        private Flight[] flightsField;
        
        /// <remarks/>
        public int AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
            }
        }
        
        /// <remarks/>
        public string AirlineName {
            get {
                return this.airlineNameField;
            }
            set {
                this.airlineNameField = value;
            }
        }
        
        /// <remarks/>
        public Flight[] Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightBooking {
        
        private int idField;
        
        private int flightIdField;
        
        private string passengerIdField;
        
        private float bookingCostField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int FlightId {
            get {
                return this.flightIdField;
            }
            set {
                this.flightIdField = value;
            }
        }
        
        /// <remarks/>
        public string PassengerId {
            get {
                return this.passengerIdField;
            }
            set {
                this.passengerIdField = value;
            }
        }
        
        /// <remarks/>
        public float BookingCost {
            get {
                return this.bookingCostField;
            }
            set {
                this.bookingCostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(_Flight))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Record {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _Flight : Record {
        
        private string airlineNameField;
        
        private string departureCityField;
        
        private string destinationCityField;
        
        private System.DateTime departureDateField;
        
        private System.DateTime returnDateField;
        
        private string[] flightTypeField;
        
        private string[] flightClassField;
        
        private float[] flightPriceField;
        
        private string planeField;
        
        /// <remarks/>
        public string AirlineName {
            get {
                return this.airlineNameField;
            }
            set {
                this.airlineNameField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureCity {
            get {
                return this.departureCityField;
            }
            set {
                this.departureCityField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReturnDate {
            get {
                return this.returnDateField;
            }
            set {
                this.returnDateField = value;
            }
        }
        
        /// <remarks/>
        public string[] FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] FlightClass {
            get {
                return this.flightClassField;
            }
            set {
                this.flightClassField = value;
            }
        }
        
        /// <remarks/>
        public float[] FlightPrice {
            get {
                return this.flightPriceField;
            }
            set {
                this.flightPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Plane {
            get {
                return this.planeField;
            }
            set {
                this.planeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightPrice {
        
        private int idField;
        
        private Flight flightField;
        
        private float valueField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Flight Flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
            }
        }
        
        /// <remarks/>
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightClass {
        
        private int idField;
        
        private Flight[] flightsField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Flight[] Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlightType {
        
        private int idField;
        
        private Flight[] flightsField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Flight[] Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void A_Debug_TestCompletedEventHandler(object sender, A_Debug_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_Debug_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_Debug_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFlightsCompletedEventHandler(object sender, GetFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void BookFlightCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetLastFlightIDCompletedEventHandler(object sender, GetLastFlightIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastFlightIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastFlightIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddFlightCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AllFlightsCompletedEventHandler(object sender, AllFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _Flight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_Flight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFlightByIdCompletedEventHandler(object sender, GetFlightByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateFlightCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteFlightCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddAirlineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAirlinesCompletedEventHandler(object sender, GetAirlinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirlinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirlinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Airline[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Airline[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteAirlineCompletedEventHandler(object sender, DeleteAirlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAirlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAirlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateAirlineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AllBookingsCompletedEventHandler(object sender, AllBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlightBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlightBooking[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetBookingsCompletedEventHandler(object sender, GetBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlightBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlightBooking[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetBookingCountCompletedEventHandler(object sender, GetBookingCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookingCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookingCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFlightCountCompletedEventHandler(object sender, GetFlightCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFlightRevenueCompletedEventHandler(object sender, GetFlightRevenueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightRevenueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightRevenueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRecentBookingsCompletedEventHandler(object sender, GetRecentBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecentBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecentBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlightBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlightBooking[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591