//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JTB_Airline_Cruise.SeaService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CruiselineServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Record))]
    public partial class CruiselineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCruisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookCruiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastCruiseIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCruiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllCruisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCruiseByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCruiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCruiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCruiselineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCruiselinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCruiselineOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCruiselineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastCruiseLineIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookingCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCruiseCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCruiseRevenueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecentBookingsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CruiselineService() {
            this.Url = global::JTB_Airline_Cruise.Properties.Settings.Default.JTB_Airline_Cruise_SeaService_CruiselineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCruisesCompletedEventHandler GetCruisesCompleted;
        
        /// <remarks/>
        public event BookCruiseCompletedEventHandler BookCruiseCompleted;
        
        /// <remarks/>
        public event GetLastCruiseIDCompletedEventHandler GetLastCruiseIDCompleted;
        
        /// <remarks/>
        public event AddCruiseCompletedEventHandler AddCruiseCompleted;
        
        /// <remarks/>
        public event AllCruisesCompletedEventHandler AllCruisesCompleted;
        
        /// <remarks/>
        public event GetCruiseByIdCompletedEventHandler GetCruiseByIdCompleted;
        
        /// <remarks/>
        public event UpdateCruiseCompletedEventHandler UpdateCruiseCompleted;
        
        /// <remarks/>
        public event DeleteCruiseCompletedEventHandler DeleteCruiseCompleted;
        
        /// <remarks/>
        public event AddCruiselineCompletedEventHandler AddCruiselineCompleted;
        
        /// <remarks/>
        public event GetCruiselinesCompletedEventHandler GetCruiselinesCompleted;
        
        /// <remarks/>
        public event DeleteCruiselineCompletedEventHandler DeleteCruiselineCompleted;
        
        /// <remarks/>
        public event UpdateCruiselineCompletedEventHandler UpdateCruiselineCompleted;
        
        /// <remarks/>
        public event GetLastCruiseLineIDCompletedEventHandler GetLastCruiseLineIDCompleted;
        
        /// <remarks/>
        public event AllBookingsCompletedEventHandler AllBookingsCompleted;
        
        /// <remarks/>
        public event GetBookingsCompletedEventHandler GetBookingsCompleted;
        
        /// <remarks/>
        public event GetBookingCountCompletedEventHandler GetBookingCountCompleted;
        
        /// <remarks/>
        public event GetCruiseCountCompletedEventHandler GetCruiseCountCompleted;
        
        /// <remarks/>
        public event GetCruiseRevenueCompletedEventHandler GetCruiseRevenueCompleted;
        
        /// <remarks/>
        public event GetRecentBookingsCompletedEventHandler GetRecentBookingsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCruises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cruise[] GetCruises(System.DateTime checkInDate, System.DateTime checkOutDate) {
            object[] results = this.Invoke("GetCruises", new object[] {
                        checkInDate,
                        checkOutDate});
            return ((Cruise[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCruisesAsync(System.DateTime checkInDate, System.DateTime checkOutDate) {
            this.GetCruisesAsync(checkInDate, checkOutDate, null);
        }
        
        /// <remarks/>
        public void GetCruisesAsync(System.DateTime checkInDate, System.DateTime checkOutDate, object userState) {
            if ((this.GetCruisesOperationCompleted == null)) {
                this.GetCruisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCruisesOperationCompleted);
            }
            this.InvokeAsync("GetCruises", new object[] {
                        checkInDate,
                        checkOutDate}, this.GetCruisesOperationCompleted, userState);
        }
        
        private void OnGetCruisesOperationCompleted(object arg) {
            if ((this.GetCruisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCruisesCompleted(this, new GetCruisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BookCruise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BookCruise(string roomType) {
            this.Invoke("BookCruise", new object[] {
                        roomType});
        }
        
        /// <remarks/>
        public void BookCruiseAsync(string roomType) {
            this.BookCruiseAsync(roomType, null);
        }
        
        /// <remarks/>
        public void BookCruiseAsync(string roomType, object userState) {
            if ((this.BookCruiseOperationCompleted == null)) {
                this.BookCruiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookCruiseOperationCompleted);
            }
            this.InvokeAsync("BookCruise", new object[] {
                        roomType}, this.BookCruiseOperationCompleted, userState);
        }
        
        private void OnBookCruiseOperationCompleted(object arg) {
            if ((this.BookCruiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookCruiseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastCruiseID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLastCruiseID() {
            object[] results = this.Invoke("GetLastCruiseID", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastCruiseIDAsync() {
            this.GetLastCruiseIDAsync(null);
        }
        
        /// <remarks/>
        public void GetLastCruiseIDAsync(object userState) {
            if ((this.GetLastCruiseIDOperationCompleted == null)) {
                this.GetLastCruiseIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastCruiseIDOperationCompleted);
            }
            this.InvokeAsync("GetLastCruiseID", new object[0], this.GetLastCruiseIDOperationCompleted, userState);
        }
        
        private void OnGetLastCruiseIDOperationCompleted(object arg) {
            if ((this.GetLastCruiseIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastCruiseIDCompleted(this, new GetLastCruiseIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCruise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCruise(_Cruise _cruise) {
            this.Invoke("AddCruise", new object[] {
                        _cruise});
        }
        
        /// <remarks/>
        public void AddCruiseAsync(_Cruise _cruise) {
            this.AddCruiseAsync(_cruise, null);
        }
        
        /// <remarks/>
        public void AddCruiseAsync(_Cruise _cruise, object userState) {
            if ((this.AddCruiseOperationCompleted == null)) {
                this.AddCruiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCruiseOperationCompleted);
            }
            this.InvokeAsync("AddCruise", new object[] {
                        _cruise}, this.AddCruiseOperationCompleted, userState);
        }
        
        private void OnAddCruiseOperationCompleted(object arg) {
            if ((this.AddCruiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCruiseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCruises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _Cruise[] AllCruises() {
            object[] results = this.Invoke("AllCruises", new object[0]);
            return ((_Cruise[])(results[0]));
        }
        
        /// <remarks/>
        public void AllCruisesAsync() {
            this.AllCruisesAsync(null);
        }
        
        /// <remarks/>
        public void AllCruisesAsync(object userState) {
            if ((this.AllCruisesOperationCompleted == null)) {
                this.AllCruisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCruisesOperationCompleted);
            }
            this.InvokeAsync("AllCruises", new object[0], this.AllCruisesOperationCompleted, userState);
        }
        
        private void OnAllCruisesOperationCompleted(object arg) {
            if ((this.AllCruisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCruisesCompleted(this, new AllCruisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCruiseById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cruise GetCruiseById(int cruiseId) {
            object[] results = this.Invoke("GetCruiseById", new object[] {
                        cruiseId});
            return ((Cruise)(results[0]));
        }
        
        /// <remarks/>
        public void GetCruiseByIdAsync(int cruiseId) {
            this.GetCruiseByIdAsync(cruiseId, null);
        }
        
        /// <remarks/>
        public void GetCruiseByIdAsync(int cruiseId, object userState) {
            if ((this.GetCruiseByIdOperationCompleted == null)) {
                this.GetCruiseByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCruiseByIdOperationCompleted);
            }
            this.InvokeAsync("GetCruiseById", new object[] {
                        cruiseId}, this.GetCruiseByIdOperationCompleted, userState);
        }
        
        private void OnGetCruiseByIdOperationCompleted(object arg) {
            if ((this.GetCruiseByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCruiseByIdCompleted(this, new GetCruiseByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCruise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCruise(_Cruise _cruise) {
            this.Invoke("UpdateCruise", new object[] {
                        _cruise});
        }
        
        /// <remarks/>
        public void UpdateCruiseAsync(_Cruise _cruise) {
            this.UpdateCruiseAsync(_cruise, null);
        }
        
        /// <remarks/>
        public void UpdateCruiseAsync(_Cruise _cruise, object userState) {
            if ((this.UpdateCruiseOperationCompleted == null)) {
                this.UpdateCruiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCruiseOperationCompleted);
            }
            this.InvokeAsync("UpdateCruise", new object[] {
                        _cruise}, this.UpdateCruiseOperationCompleted, userState);
        }
        
        private void OnUpdateCruiseOperationCompleted(object arg) {
            if ((this.UpdateCruiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCruiseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCruise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCruise(int cruiseId) {
            this.Invoke("DeleteCruise", new object[] {
                        cruiseId});
        }
        
        /// <remarks/>
        public void DeleteCruiseAsync(int cruiseId) {
            this.DeleteCruiseAsync(cruiseId, null);
        }
        
        /// <remarks/>
        public void DeleteCruiseAsync(int cruiseId, object userState) {
            if ((this.DeleteCruiseOperationCompleted == null)) {
                this.DeleteCruiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCruiseOperationCompleted);
            }
            this.InvokeAsync("DeleteCruise", new object[] {
                        cruiseId}, this.DeleteCruiseOperationCompleted, userState);
        }
        
        private void OnDeleteCruiseOperationCompleted(object arg) {
            if ((this.DeleteCruiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCruiseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCruiseline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCruiseline(string cruiselineName) {
            this.Invoke("AddCruiseline", new object[] {
                        cruiselineName});
        }
        
        /// <remarks/>
        public void AddCruiselineAsync(string cruiselineName) {
            this.AddCruiselineAsync(cruiselineName, null);
        }
        
        /// <remarks/>
        public void AddCruiselineAsync(string cruiselineName, object userState) {
            if ((this.AddCruiselineOperationCompleted == null)) {
                this.AddCruiselineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCruiselineOperationCompleted);
            }
            this.InvokeAsync("AddCruiseline", new object[] {
                        cruiselineName}, this.AddCruiselineOperationCompleted, userState);
        }
        
        private void OnAddCruiselineOperationCompleted(object arg) {
            if ((this.AddCruiselineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCruiselineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCruiselines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _Cruiseline[] GetCruiselines() {
            object[] results = this.Invoke("GetCruiselines", new object[0]);
            return ((_Cruiseline[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCruiselinesAsync() {
            this.GetCruiselinesAsync(null);
        }
        
        /// <remarks/>
        public void GetCruiselinesAsync(object userState) {
            if ((this.GetCruiselinesOperationCompleted == null)) {
                this.GetCruiselinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCruiselinesOperationCompleted);
            }
            this.InvokeAsync("GetCruiselines", new object[0], this.GetCruiselinesOperationCompleted, userState);
        }
        
        private void OnGetCruiselinesOperationCompleted(object arg) {
            if ((this.GetCruiselinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCruiselinesCompleted(this, new GetCruiselinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCruiseline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteCruiseline(int cruiselineId) {
            object[] results = this.Invoke("DeleteCruiseline", new object[] {
                        cruiselineId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCruiselineAsync(int cruiselineId) {
            this.DeleteCruiselineAsync(cruiselineId, null);
        }
        
        /// <remarks/>
        public void DeleteCruiselineAsync(int cruiselineId, object userState) {
            if ((this.DeleteCruiselineOperationCompleted == null)) {
                this.DeleteCruiselineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCruiselineOperationCompleted);
            }
            this.InvokeAsync("DeleteCruiseline", new object[] {
                        cruiselineId}, this.DeleteCruiselineOperationCompleted, userState);
        }
        
        private void OnDeleteCruiselineOperationCompleted(object arg) {
            if ((this.DeleteCruiselineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCruiselineCompleted(this, new DeleteCruiselineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCruiseline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCruiseline(int cruiselineId, string cruiselineName) {
            this.Invoke("UpdateCruiseline", new object[] {
                        cruiselineId,
                        cruiselineName});
        }
        
        /// <remarks/>
        public void UpdateCruiselineAsync(int cruiselineId, string cruiselineName) {
            this.UpdateCruiselineAsync(cruiselineId, cruiselineName, null);
        }
        
        /// <remarks/>
        public void UpdateCruiselineAsync(int cruiselineId, string cruiselineName, object userState) {
            if ((this.UpdateCruiselineOperationCompleted == null)) {
                this.UpdateCruiselineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCruiselineOperationCompleted);
            }
            this.InvokeAsync("UpdateCruiseline", new object[] {
                        cruiselineId,
                        cruiselineName}, this.UpdateCruiselineOperationCompleted, userState);
        }
        
        private void OnUpdateCruiselineOperationCompleted(object arg) {
            if ((this.UpdateCruiselineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCruiselineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastCruiseLineID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLastCruiseLineID() {
            object[] results = this.Invoke("GetLastCruiseLineID", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastCruiseLineIDAsync() {
            this.GetLastCruiseLineIDAsync(null);
        }
        
        /// <remarks/>
        public void GetLastCruiseLineIDAsync(object userState) {
            if ((this.GetLastCruiseLineIDOperationCompleted == null)) {
                this.GetLastCruiseLineIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastCruiseLineIDOperationCompleted);
            }
            this.InvokeAsync("GetLastCruiseLineID", new object[0], this.GetLastCruiseLineIDOperationCompleted, userState);
        }
        
        private void OnGetLastCruiseLineIDOperationCompleted(object arg) {
            if ((this.GetLastCruiseLineIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastCruiseLineIDCompleted(this, new GetLastCruiseLineIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CruiseBooking[] AllBookings() {
            object[] results = this.Invoke("AllBookings", new object[0]);
            return ((CruiseBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void AllBookingsAsync() {
            this.AllBookingsAsync(null);
        }
        
        /// <remarks/>
        public void AllBookingsAsync(object userState) {
            if ((this.AllBookingsOperationCompleted == null)) {
                this.AllBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllBookingsOperationCompleted);
            }
            this.InvokeAsync("AllBookings", new object[0], this.AllBookingsOperationCompleted, userState);
        }
        
        private void OnAllBookingsOperationCompleted(object arg) {
            if ((this.AllBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllBookingsCompleted(this, new AllBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CruiseBooking[] GetBookings(string passengerId) {
            object[] results = this.Invoke("GetBookings", new object[] {
                        passengerId});
            return ((CruiseBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBookingsAsync(string passengerId) {
            this.GetBookingsAsync(passengerId, null);
        }
        
        /// <remarks/>
        public void GetBookingsAsync(string passengerId, object userState) {
            if ((this.GetBookingsOperationCompleted == null)) {
                this.GetBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookingsOperationCompleted);
            }
            this.InvokeAsync("GetBookings", new object[] {
                        passengerId}, this.GetBookingsOperationCompleted, userState);
        }
        
        private void OnGetBookingsOperationCompleted(object arg) {
            if ((this.GetBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookingsCompleted(this, new GetBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookingCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetBookingCount() {
            object[] results = this.Invoke("GetBookingCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookingCountAsync() {
            this.GetBookingCountAsync(null);
        }
        
        /// <remarks/>
        public void GetBookingCountAsync(object userState) {
            if ((this.GetBookingCountOperationCompleted == null)) {
                this.GetBookingCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookingCountOperationCompleted);
            }
            this.InvokeAsync("GetBookingCount", new object[0], this.GetBookingCountOperationCompleted, userState);
        }
        
        private void OnGetBookingCountOperationCompleted(object arg) {
            if ((this.GetBookingCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookingCountCompleted(this, new GetBookingCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCruiseCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCruiseCount() {
            object[] results = this.Invoke("GetCruiseCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCruiseCountAsync() {
            this.GetCruiseCountAsync(null);
        }
        
        /// <remarks/>
        public void GetCruiseCountAsync(object userState) {
            if ((this.GetCruiseCountOperationCompleted == null)) {
                this.GetCruiseCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCruiseCountOperationCompleted);
            }
            this.InvokeAsync("GetCruiseCount", new object[0], this.GetCruiseCountOperationCompleted, userState);
        }
        
        private void OnGetCruiseCountOperationCompleted(object arg) {
            if ((this.GetCruiseCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCruiseCountCompleted(this, new GetCruiseCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCruiseRevenue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float GetCruiseRevenue() {
            object[] results = this.Invoke("GetCruiseRevenue", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void GetCruiseRevenueAsync() {
            this.GetCruiseRevenueAsync(null);
        }
        
        /// <remarks/>
        public void GetCruiseRevenueAsync(object userState) {
            if ((this.GetCruiseRevenueOperationCompleted == null)) {
                this.GetCruiseRevenueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCruiseRevenueOperationCompleted);
            }
            this.InvokeAsync("GetCruiseRevenue", new object[0], this.GetCruiseRevenueOperationCompleted, userState);
        }
        
        private void OnGetCruiseRevenueOperationCompleted(object arg) {
            if ((this.GetCruiseRevenueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCruiseRevenueCompleted(this, new GetCruiseRevenueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecentBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CruiseBooking[] GetRecentBookings() {
            object[] results = this.Invoke("GetRecentBookings", new object[0]);
            return ((CruiseBooking[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecentBookingsAsync() {
            this.GetRecentBookingsAsync(null);
        }
        
        /// <remarks/>
        public void GetRecentBookingsAsync(object userState) {
            if ((this.GetRecentBookingsOperationCompleted == null)) {
                this.GetRecentBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecentBookingsOperationCompleted);
            }
            this.InvokeAsync("GetRecentBookings", new object[0], this.GetRecentBookingsOperationCompleted, userState);
        }
        
        private void OnGetRecentBookingsOperationCompleted(object arg) {
            if ((this.GetRecentBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecentBookingsCompleted(this, new GetRecentBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cruise {
        
        private int cruiseIDField;
        
        private string nameField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private Cruiseline cruiselineField;
        
        private string shipField;
        
        private int cruiseLengthField;
        
        private string departurePortField;
        
        private VisitingPort[] visitingPortsField;
        
        private CruisePrice[] cruisePriceField;
        
        private RoomType[] roomTypesField;
        
        /// <remarks/>
        public int CruiseID {
            get {
                return this.cruiseIDField;
            }
            set {
                this.cruiseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public Cruiseline Cruiseline {
            get {
                return this.cruiselineField;
            }
            set {
                this.cruiselineField = value;
            }
        }
        
        /// <remarks/>
        public string Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
        
        /// <remarks/>
        public int CruiseLength {
            get {
                return this.cruiseLengthField;
            }
            set {
                this.cruiseLengthField = value;
            }
        }
        
        /// <remarks/>
        public string DeparturePort {
            get {
                return this.departurePortField;
            }
            set {
                this.departurePortField = value;
            }
        }
        
        /// <remarks/>
        public VisitingPort[] VisitingPorts {
            get {
                return this.visitingPortsField;
            }
            set {
                this.visitingPortsField = value;
            }
        }
        
        /// <remarks/>
        public CruisePrice[] CruisePrice {
            get {
                return this.cruisePriceField;
            }
            set {
                this.cruisePriceField = value;
            }
        }
        
        /// <remarks/>
        public RoomType[] RoomTypes {
            get {
                return this.roomTypesField;
            }
            set {
                this.roomTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cruiseline {
        
        private int cruiselineIDField;
        
        private string cruiselineNameField;
        
        private Cruise[] cruisesField;
        
        /// <remarks/>
        public int CruiselineID {
            get {
                return this.cruiselineIDField;
            }
            set {
                this.cruiselineIDField = value;
            }
        }
        
        /// <remarks/>
        public string CruiselineName {
            get {
                return this.cruiselineNameField;
            }
            set {
                this.cruiselineNameField = value;
            }
        }
        
        /// <remarks/>
        public Cruise[] Cruises {
            get {
                return this.cruisesField;
            }
            set {
                this.cruisesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CruiseBooking {
        
        private int idField;
        
        private int cruiseIdField;
        
        private int cruiseNameField;
        
        private string roomNumberField;
        
        private string nameField;
        
        private System.DateTime checkInDateField;
        
        private System.DateTime checkOutDateField;
        
        private string departureField;
        
        private string destinationField;
        
        private string passengerIdField;
        
        private string passengerNameField;
        
        private float bookingCostField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int CruiseId {
            get {
                return this.cruiseIdField;
            }
            set {
                this.cruiseIdField = value;
            }
        }
        
        /// <remarks/>
        public int CruiseName {
            get {
                return this.cruiseNameField;
            }
            set {
                this.cruiseNameField = value;
            }
        }
        
        /// <remarks/>
        public string RoomNumber {
            get {
                return this.roomNumberField;
            }
            set {
                this.roomNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CheckOutDate {
            get {
                return this.checkOutDateField;
            }
            set {
                this.checkOutDateField = value;
            }
        }
        
        /// <remarks/>
        public string Departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
            }
        }
        
        /// <remarks/>
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string PassengerId {
            get {
                return this.passengerIdField;
            }
            set {
                this.passengerIdField = value;
            }
        }
        
        /// <remarks/>
        public string PassengerName {
            get {
                return this.passengerNameField;
            }
            set {
                this.passengerNameField = value;
            }
        }
        
        /// <remarks/>
        public float BookingCost {
            get {
                return this.bookingCostField;
            }
            set {
                this.bookingCostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(_Cruiseline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(_Cruise))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Record {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _Cruiseline : Record {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _Cruise : Record {
        
        private string cruiselineField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string shipField;
        
        private int cruiseLengthField;
        
        private string departurePortField;
        
        private string[] visitingPortsField;
        
        private float[] cruisePriceField;
        
        private string[] roomTypesField;
        
        /// <remarks/>
        public string Cruiseline {
            get {
                return this.cruiselineField;
            }
            set {
                this.cruiselineField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
        
        /// <remarks/>
        public int CruiseLength {
            get {
                return this.cruiseLengthField;
            }
            set {
                this.cruiseLengthField = value;
            }
        }
        
        /// <remarks/>
        public string DeparturePort {
            get {
                return this.departurePortField;
            }
            set {
                this.departurePortField = value;
            }
        }
        
        /// <remarks/>
        public string[] VisitingPorts {
            get {
                return this.visitingPortsField;
            }
            set {
                this.visitingPortsField = value;
            }
        }
        
        /// <remarks/>
        public float[] CruisePrice {
            get {
                return this.cruisePriceField;
            }
            set {
                this.cruisePriceField = value;
            }
        }
        
        /// <remarks/>
        public string[] RoomTypes {
            get {
                return this.roomTypesField;
            }
            set {
                this.roomTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RoomType {
        
        private int idField;
        
        private Cruise cruiseField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Cruise Cruise {
            get {
                return this.cruiseField;
            }
            set {
                this.cruiseField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CruisePrice {
        
        private int idField;
        
        private Cruise cruiseField;
        
        private float priceField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Cruise Cruise {
            get {
                return this.cruiseField;
            }
            set {
                this.cruiseField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VisitingPort {
        
        private int idField;
        
        private Cruise cruiseField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Cruise Cruise {
            get {
                return this.cruiseField;
            }
            set {
                this.cruiseField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCruisesCompletedEventHandler(object sender, GetCruisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCruisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCruisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cruise[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cruise[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void BookCruiseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetLastCruiseIDCompletedEventHandler(object sender, GetLastCruiseIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastCruiseIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastCruiseIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddCruiseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AllCruisesCompletedEventHandler(object sender, AllCruisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllCruisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllCruisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _Cruise[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_Cruise[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCruiseByIdCompletedEventHandler(object sender, GetCruiseByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCruiseByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCruiseByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cruise Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cruise)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateCruiseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteCruiseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddCruiselineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCruiselinesCompletedEventHandler(object sender, GetCruiselinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCruiselinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCruiselinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _Cruiseline[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_Cruiseline[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteCruiselineCompletedEventHandler(object sender, DeleteCruiselineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCruiselineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCruiselineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateCruiselineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetLastCruiseLineIDCompletedEventHandler(object sender, GetLastCruiseLineIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastCruiseLineIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastCruiseLineIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AllBookingsCompletedEventHandler(object sender, AllBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CruiseBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CruiseBooking[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetBookingsCompletedEventHandler(object sender, GetBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CruiseBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CruiseBooking[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetBookingCountCompletedEventHandler(object sender, GetBookingCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookingCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookingCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCruiseCountCompletedEventHandler(object sender, GetCruiseCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCruiseCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCruiseCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCruiseRevenueCompletedEventHandler(object sender, GetCruiseRevenueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCruiseRevenueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCruiseRevenueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRecentBookingsCompletedEventHandler(object sender, GetRecentBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecentBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecentBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CruiseBooking[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CruiseBooking[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591